### PR TITLE
Added a bouncy ball, for bouncyness

### PR DESCRIPTION
**Pull request by timoreo22**
This adds a bouncy ball

- [x] The ball is bouncy
- [x] You can throw the ball 
- [x] The ball has a fancy trail
- [x] The ball also has touch controls ! phone compatibility !! 
- [x] Responsive view !
- [x] Basketball mode !
- [x] The ball ROTATE 
- [ ] ~~If you are on another tab, the ball may randomly start bouncing if it was on the ground, sometimes it goes hyperspeed~~
	- has been fixed

What more could you want ?

### CODE REVIEW

**Comment by Xenthys** [comment]
Does the ball rotate when it collides with something?

**Comment by timoreo22** [comment]
it does now

**Comment by timoreo22** [comment]
Demo url : https://timoreo22.github.io/tacobandit744.github.io/

**Comment by tacobandit744** [comment]
Time to play some Bball

**Pull request merged**
